version: 2

sources:
  - name: AIRBNB_BORDEAUX
    database: AIRBNB_BI  
    schema: RAW_AIRBNB_BORDEAUX  
    tables:
      - name: DBO_LISTING
      - name: DBO_REVIEW
  - name: AIRBNB_LYON
    database: AIRBNB_BI  
    schema: RAW_AIRBNB_LYON 
    tables:
      - name: AIRBNB_LISTING
      - name: AIRBNB_REVIEW
  - name: AIRBNB_PARIS
    database: AIRBNB_BI  
    schema: RAW_AIRBNB_PARIS
    tables:
      - name: AIRBNB_LISTING
      - name: AIRBNB_REVIEW
  - name: AIRBNB_PAYS_BASQUE
    database: AIRBNB_BI  
    schema: RAW_AIRBNB_PAYS_BASQUE
    tables:
      - name: AIRBNB_LISTING
      - name: AIRBNB_REVIEW